// Fetcher and Parser for The Penguins Club Events GitHub Issues
// Source Repository: https://github.com/the-penguins-club/events/issues

import {
  events as seedEvents,
  type CommunityEvent,
  type EventAgendaItem,
  type EventSpeaker,
  type EventFaq
} from '../data/events';

export interface GitHubIssue {
  id: number;
  number: number;
  title: string;
  state: 'open' | 'closed';
  body: string | null;
  labels: Array<{ name: string } | string>;
  html_url: string;
  pull_request?: unknown;
  created_at: string;
  updated_at: string;
}

const GITHUB_REPO = 'the-penguins-club/events';
const GITHUB_API_URL = `https://api.github.com/repos/${GITHUB_REPO}/issues?state=all&per_page=100`;

/**
 * Normalizes title string into a clean URL-friendly slug
 */
function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/^\[event\]:\s*/i, '')
    .trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_-]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * Parses section blocks generated by GitHub Issue Forms (### or ## Label \n\n Content)
 * Also extracts any top-level YAML frontmatter or YAML code block.
 */
function parseIssueFormSections(body: string): Record<string, string> {
  const sections: Record<string, string> = {};

  // 1. Extract any top-level YAML frontmatter or ```yaml ``` block
  const yamlBlockMatch = body.match(/^(?:---[\r\n]+([\s\S]*?)[\r\n]+---|```ya?ml[\r\n]+([\s\S]*?)```)/);
  if (yamlBlockMatch) {
    const yamlContent = yamlBlockMatch[1] || yamlBlockMatch[2] || '';
    const yamlLines = yamlContent.split('\n');
    for (const rawLine of yamlLines) {
      const line = rawLine.trim();
      if (!line || line.startsWith('#') || line.startsWith('-')) continue;
      const colonIndex = line.indexOf(':');
      if (colonIndex > 0) {
        const key = line.slice(0, colonIndex).trim().toLowerCase();
        let val = line.slice(colonIndex + 1).trim();
        if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
          val = val.slice(1, -1);
        }
        sections[key] = val;
      }
    }
  }

  // 2. Extract markdown heading sections (both ## and ###)
  const headingRegex = /^#{2,3}\s+(.+)$/gm;
  const matches: Array<{ title: string; index: number; contentStart: number }> = [];

  let match: RegExpExecArray | null;
  while ((match = headingRegex.exec(body)) !== null) {
    matches.push({
      title: match[1].trim().toLowerCase(),
      index: match.index,
      contentStart: match.index + match[0].length
    });
  }

  for (let i = 0; i < matches.length; i++) {
    const current = matches[i];
    const next = matches[i + 1];
    const rawContent = next
      ? body.substring(current.contentStart, next.index)
      : body.substring(current.contentStart);

    sections[current.title] = rawContent.trim();
  }

  return sections;
}

/**
 * Helper to extract bulleted lines into clean string array
 */
function parseBulletList(text: string): string[] {
  if (!text) return [];
  return text
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && (line.startsWith('-') || line.startsWith('*') || /^\d+\./.test(line)))
    .map((line) => line.replace(/^[-*]\s+|\d+\.\s+/, '').trim())
    .filter((line) => line.length > 0 && !line.startsWith('_No response_'));
}

/**
 * Parses simple YAML list of objects from text
 */
function parseYamlObjects<T>(text: string): T[] {
  if (!text || text.includes('_No response_')) return [];
  const cleanText = text.replace(/```(?:ya?ml)?/g, '').trim();
  const items: T[] = [];
  const blocks = cleanText.split(/\n(?=-\s+)/);

  for (const block of blocks) {
    if (!block.trim()) continue;
    const item: Record<string, string> = {};
    const lines = block.split('\n');

    for (const rawLine of lines) {
      const line = rawLine.replace(/^-\s+/, '').trim();
      const colonIndex = line.indexOf(':');
      if (colonIndex > 0) {
        const key = line.slice(0, colonIndex).trim();
        let val = line.slice(colonIndex + 1).trim();
        // Strip surrounding quotes
        if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
          val = val.slice(1, -1);
        }
        item[key] = val;
      }
    }

    if (Object.keys(item).length > 0) {
      items.push(item as unknown as T);
    }
  }

  return items;
}

/**
 * Parses markdown table into structured objects
 */
function parseMarkdownTable(text: string): Array<Record<string, string>> {
  if (!text.includes('|')) return [];
  const lines = text
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l.startsWith('|') && l.endsWith('|'));
  if (lines.length < 3) return [];

  const headers = lines[0]
    .split('|')
    .slice(1, -1)
    .map((h) => h.trim().toLowerCase());
  const rows: Array<Record<string, string>> = [];

  for (let i = 2; i < lines.length; i++) {
    const cols = lines[i]
      .split('|')
      .slice(1, -1)
      .map((c) => c.trim());
    const obj: Record<string, string> = {};
    headers.forEach((h, idx) => {
      obj[h] = cols[idx] || '';
    });
    rows.push(obj);
  }

  return rows;
}

/**
 * Parses an agenda section (supports YAML list or Markdown table)
 */
function parseAgenda(text: string): EventAgendaItem[] {
  if (!text) return [];
  const yamlItems = parseYamlObjects<EventAgendaItem>(text);
  if (yamlItems.length > 0 && yamlItems[0].time && yamlItems[0].title) {
    return yamlItems;
  }

  const tableRows = parseMarkdownTable(text);
  if (tableRows.length > 0) {
    return tableRows.map((row) => ({
      time: row.time || '',
      title: row.title || row.session || '',
      speaker: row.speaker || undefined,
      description: row.description || undefined
    }));
  }

  return [];
}

/**
 * Parses speakers section (supports YAML list or Markdown table)
 */
function parseSpeakers(text: string): EventSpeaker[] {
  if (!text) return [];
  const yamlItems = parseYamlObjects<EventSpeaker>(text);
  if (yamlItems.length > 0 && yamlItems[0].name) {
    return yamlItems;
  }

  const tableRows = parseMarkdownTable(text);
  if (tableRows.length > 0) {
    return tableRows.map((row) => ({
      name: row.name || '',
      role: row.role || 'Community Host',
      github: row.github || undefined,
      bio: row.bio || undefined,
      avatar: row.avatar || undefined
    }));
  }

  return [];
}

/**
 * Parses FAQs section (supports YAML list or Q&A markdown)
 */
function parseFaqs(text: string): EventFaq[] {
  if (!text) return [];
  const yamlItems = parseYamlObjects<EventFaq>(text);
  if (yamlItems.length > 0 && yamlItems[0].question && yamlItems[0].answer) {
    return yamlItems;
  }

  // Parse Q: ... \n A: ... pattern
  const faqs: EventFaq[] = [];
  const pairs = text.split(/(?:^|\n)(?=###?\s*Q:|Q:)/gi);

  for (const pair of pairs) {
    const qMatch = pair.match(/(?:###?\s*Q:|Q:)\s*(.+)/i);
    const aMatch = pair.match(/(?:###?\s*A:|A:)\s*([\s\S]+)/i);
    if (qMatch && aMatch) {
      faqs.push({
        question: qMatch[1].trim(),
        answer: aMatch[1].trim()
      });
    }
  }

  return faqs;
}

/**
 * Parses an issue body into a valid CommunityEvent object
 */
export function parseEventIssue(issue: GitHubIssue): CommunityEvent | null {
  const body = issue.body;
  if (!body) return null;

  const sections = parseIssueFormSections(body);

  // Helper to match flexible section keys
  const getSection = (...keys: string[]): string => {
    for (const key of keys) {
      const lower = key.toLowerCase();
      for (const [sKey, val] of Object.entries(sections)) {
        if (sKey.includes(lower)) return val;
      }
    }
    return '';
  };

  const titleRaw = getSection('event title', 'title') || issue.title.replace(/^\[event\]:\s*/i, '');
  const title = titleRaw.trim();
  if (!title) return null;

  const slugRaw = getSection('url slug', 'slug');
  const slug = slugRaw && !slugRaw.includes('_No response_') ? slugify(slugRaw) : slugify(title);

  const trackTag = getSection('track / category tag', 'track_tag', 'track') || 'GNU/LINUX & OPEN SOURCE';
  const startDateIso = getSection('start date & time', 'start_date_iso', 'start') || new Date().toISOString();
  const endDateIso = getSection('end date & time', 'end_date_iso', 'end') || new Date(Date.now() + 4 * 3600 * 1000).toISOString();
  const timeString = getSection('human-readable time string', 'time_string', 'timing') || 'Saturday • 15:00 BST';
  const location = getSection('location', 'general venue') || 'Dhaka, Bangladesh';
  const venueName = getSection('exact venue name', 'venue_name', 'venue') || location;
  const venueAddress = getSection('venue physical address', 'venue_address', 'address') || location;

  const rawVenueType = getSection('venue type', 'venue_type').toLowerCase();
  const venueType: CommunityEvent['venueType'] =
    rawVenueType.includes('outdoor') ? 'outdoor' :
    rawVenueType.includes('virtual') ? 'virtual' :
    rawVenueType.includes('hybrid') ? 'hybrid' : 'in-person';

  const rawTheme = getSection('visual color theme', 'theme').toLowerCase();
  const theme: CommunityEvent['theme'] =
    rawTheme.includes('grass') ? 'grass' :
    rawTheme.includes('hacktoberfest') ? 'hacktoberfest' :
    rawTheme.includes('git') ? 'git' :
    rawTheme.includes('selfhost') ? 'selfhost' : 'linux';

  const isSuper = getSection('is this a super event', 'is_super').toLowerCase().includes('true');
  const superBadge = getSection('super event badge label', 'super_badge') || (isSuper ? 'SUPER EVENT 🌿' : undefined);
  const cost = getSection('admission fee', 'cost') || '100% Free • Open to All';
  const capacityRaw = getSection('venue capacity', 'capacity');
  const capacity = capacityRaw && !capacityRaw.includes('_No response_') ? capacityRaw : undefined;
  const registrationUrl = getSection('registration / rsvp url', 'registration_url', 'rsvp') || 'https://t.me/penguinsclubnetwork';
  const imageRaw = getSection('event banner graphic', 'image');
  const image = imageRaw && !imageRaw.includes('_No response_') ? imageRaw : '/images/meetups/meetup-linux-intro.svg';

  const description = getSection('short summary', 'description') || 'A community-driven Linux and open source meetup in Dhaka.';

  const fullOverviewRaw = getSection('full overview paragraphs', 'full_overview', 'overview');
  const fullOverview = fullOverviewRaw
    ? fullOverviewRaw
        .split(/\n\s*\n/)
        .map((p) => p.trim())
        .filter((p) => p.length > 0 && !p.startsWith('_No response_'))
    : [description];

  const highlights = parseBulletList(getSection('key highlights & activities', 'highlights'));
  const agenda = parseAgenda(getSection('schedule & agenda timeline', 'agenda', 'schedule'));
  const prerequisites = parseBulletList(getSection('prerequisites', 'requirements'));
  const whatToBring = parseBulletList(getSection('what to bring', 'items to bring'));
  const speakers = parseSpeakers(getSection('facilitators & speakers', 'speakers', 'mentors'));
  const faqs = parseFaqs(getSection('frequently asked questions', 'faqs', 'faq'));

  // Formatted date badge
  let dateBadge = `${new Date(startDateIso).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })} • BST`;
  try {
    const d = new Date(startDateIso);
    if (!isNaN(d.getTime())) {
      dateBadge = `${d.getDate().toString().padStart(2, '0')} ${d.toLocaleString('en-US', { month: 'long' })} ${d.getFullYear()} • ${d.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })} BST`;
    }
  } catch {
    // keep default
  }

  // RFC 5545 format strings for Calendar
  const calStart = startDateIso.replace(/[-:]/g, '').split('.')[0] + 'Z';
  const calEnd = endDateIso.replace(/[-:]/g, '').split('.')[0] + 'Z';

  return {
    slug,
    id: `github-event-${issue.number}`,
    title,
    trackTag,
    dateBadge,
    startDateIso,
    endDateIso,
    timeString,
    location,
    venueName,
    venueAddress,
    venueType,
    image,
    description,
    fullOverview,
    highlights: highlights.length > 0 ? highlights : ['Hands-on peer learning and collaboration.'],
    agenda: agenda.length > 0 ? agenda : [{ time: timeString, title: 'Main Session & Collaborative Lab' }],
    prerequisites: prerequisites.length > 0 ? prerequisites : ['Curiosity about GNU/Linux and open source software.'],
    whatToBring: whatToBring.length > 0 ? whatToBring : ['Laptop with Linux installed or a bootable USB drive.'],
    speakers,
    faqs,
    isSuper,
    superBadge,
    theme,
    calTitle: title,
    calStart,
    calEnd,
    calLocation: venueAddress,
    registrationUrl,
    capacity,
    cost
  };
}

/**
 * Fetches events from GitHub repo issues (https://github.com/the-penguins-club/events/issues).
 * Falls back safely to bundled seed events if GitHub is unreachable, rate-limited, or empty.
 */
export async function fetchEventsFromGitHub(): Promise<CommunityEvent[]> {
  try {
    const headers: Record<string, string> = {
      Accept: 'application/vnd.github.v3+json',
      'User-Agent': 'The-Penguins-Club-Events-Engine'
    };

    // Support optional GitHub token for higher rate limits (5000/hr)
    const token =
      import.meta.env?.GITHUB_TOKEN ||
      import.meta.env?.TPC_GITHUB_TOKEN ||
      (typeof process !== 'undefined' && (process.env?.GITHUB_TOKEN || process.env?.TPC_GITHUB_TOKEN)) ||
      undefined;

    if (token) {
      headers.Authorization = `Bearer ${token}`;
    }

    const response = await fetch(GITHUB_API_URL, { headers });

    if (!response.ok) {
      console.warn(`[GitHub Events] API returned HTTP ${response.status}. Using fallback seed events.`);
      return seedEvents;
    }

    const issues: GitHubIssue[] = await response.json();
    if (!Array.isArray(issues)) {
      return seedEvents;
    }

    // Filter only event issues (exclude PRs and closed issues if desired)
    const eventIssues = issues.filter((issue) => {
      if (issue.pull_request) return false;
      const hasEventLabel = Array.isArray(issue.labels) && issue.labels.some((l) => (typeof l === 'string' ? l : l.name).toLowerCase() === 'event');
      const hasEventTitle = issue.title.toLowerCase().startsWith('[event]');
      return hasEventLabel || hasEventTitle;
    });

    if (eventIssues.length === 0) {
      return seedEvents;
    }

    const parsedEvents: CommunityEvent[] = [];
    for (const issue of eventIssues) {
      const parsed = parseEventIssue(issue);
      if (parsed) {
        parsedEvents.push(parsed);
      }
    }

    if (parsedEvents.length === 0) {
      return seedEvents;
    }

    // Merge GitHub events with seed events (deduplicating by slug)
    const eventMap = new Map<string, CommunityEvent>();

    // Seed events first
    for (const ev of seedEvents) {
      eventMap.set(ev.slug, ev);
    }

    // GitHub events take precedence or add new ones
    for (const ev of parsedEvents) {
      eventMap.set(ev.slug, ev);
    }

    return Array.from(eventMap.values());
  } catch (err) {
    console.warn('[GitHub Events] Error fetching from GitHub issues:', err);
    return seedEvents;
  }
}
